"""
Omniverse Digital Twin Streamer (World State Controller)
========================================================
Acts as the bidirectional bridge between SmartCAPEX UI and NVIDIA Omniverse.
Reads the static USDA mesh generated by RetrosimHullAdapter and dynamically
animates parameters (heave, pitch) based on EANN predictions or Modulus physics.

Dependencies:
- pxr (usd-core) - Install using `pip install usd-core`
"""

import os
import time
import math

# Requires pxr (USD) library
try:
    from pxr import Usd, UsdGeom, Gf, Sdf
    HAS_USD = True
except ImportError:
    HAS_USD = False

class OmniverseStreamer:
    def __init__(self, usd_path: str):
        self.usd_path = usd_path
        self.stage = None
        
        if HAS_USD and os.path.exists(self.usd_path):
            self.stage = Usd.Stage.Open(self.usd_path)
            print(f"🌍 Omniverse World State connected to: {self.usd_path}")
        else:
            print("⚠️ pxr module absent or USD file not found. Streamer in disconnected mode.")

    def update_environmental_state(self, wave_height: float, ship_speed: float):
        """
        Dynamically adjusts the ship's Z-axis (Heave) and Y-rotation (Pitch)
        to simulate movement through waves in the Omniverse viewer.
        """
        if not self.stage:
            return

        # Target the top-level Hull Xform (created in hull_adapter.usda)
        prim = self.stage.GetPrimAtPath("/Hull_Xform")
        if not prim.IsValid():
            print("❌ Valid Xform prim not found in USD.")
            return

        xformable = UsdGeom.Xformable(prim)
        
        # Clear existing ops to avoid duplications
        xformable.ClearXformOpOrder()
        
        # Add Translation Operation (Heave/Sway/Surge)
        translate_op = xformable.AddTranslateOp()
        
        # Add Rotation Operation (Pitch/Roll/Yaw)
        rotate_op = xformable.AddRotateXYZOp()

        # Simulate 10 frames of wave motion
        print("🌊 Starting Digital Twin USD animation...")
        for frame in range(0, 60):
            time_sec = frame * 0.1
            
            # Simple harmonic oscillator for heave
            heave = (wave_height / 2.0) * math.sin(ship_speed * time_sec)
            translate_op.Set(Gf.Vec3d(0, 0, heave), Usd.TimeCode(frame))
            
            # Simple harmonic oscillator for pitch
            pitch = (wave_height * 2.5) * math.cos(ship_speed * time_sec)
            rotate_op.Set(Gf.Vec3d(0, pitch, 0), Usd.TimeCode(frame))
        
        # Set stage metadata
        self.stage.SetStartTimeCode(0)
        self.stage.SetEndTimeCode(60)
        
        # Save modifications live to the USD
        self.stage.GetRootLayer().Save()
        print("✅ Omniverse scene updated with environmental physics.")

    def inject_modulus_cfd_results(self, u_field, p_field):
        """
        Phase 2 Goal: Reads output from ModulusCFDAgent and writes
        velocity streamlines and pressure colors directly into the USD.
        """
        pass

if __name__ == "__main__":
    # Example execution
    streamer = OmniverseStreamer(
        usd_path=os.path.join("..", "models", "geometry", "generated_hull.usda")
    )
    # Simulate a 2.5m wave at 12 knots
    streamer.update_environmental_state(wave_height=2.5, ship_speed=12.0)
